// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4qi8Es2jgbBTgZfKcS7knI4uI7ubyGw',
    appId: '1:681703183588:web:2f61c581a54c65aef548f1',
    messagingSenderId: '681703183588',
    projectId: 'target-b2071',
    authDomain: 'target-b2071.firebaseapp.com',
    storageBucket: 'target-b2071.appspot.com',
    measurementId: 'G-ENBG9FKNWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BvEWwnwR2OcAR41PtkZwxsgX6bSm5VI',
    appId: '1:681703183588:android:30a5e71d961ea187f548f1',
    messagingSenderId: '681703183588',
    projectId: 'target-b2071',
    storageBucket: 'target-b2071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0R37XsWw3CU1FN2ekQH5sc63yXe5gDNs',
    appId: '1:681703183588:ios:44f1850e3b420e47f548f1',
    messagingSenderId: '681703183588',
    projectId: 'target-b2071',
    storageBucket: 'target-b2071.appspot.com',
    iosBundleId: 'com.example.targetSistemasTestflutterDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0R37XsWw3CU1FN2ekQH5sc63yXe5gDNs',
    appId: '1:681703183588:ios:ca242dce86797bbcf548f1',
    messagingSenderId: '681703183588',
    projectId: 'target-b2071',
    storageBucket: 'target-b2071.appspot.com',
    iosBundleId: 'com.example.targetSistemasTestflutterDev.RunnerTests',
  );
}
